server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://45.77.165.20:15433/postgres?characterEncoding=utf8&useSSL=false
        username: postgres
        password: 18739548870yu
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: update
        show-sql: true
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        servlet:
            content-type: text/html
        cache: false
        encoding: UTF-8
    resources:
        static-locations: classpath:/static/
